### ISSUE TITLE
Practica de prototipo de Realidad Aumentada

### ISSUE THREAD

**Issue by Jaci14** [SistemasTecTlaxiaco/diseno-de-prototipo-de-realidad-aumentada-equipo-jaciel#2]
[Reporte de prototipo RA.pdf](https://github.com/SistemasTecTlaxiaco/diseno-de-prototipo-de-realidad-aumentada-equipo-jaciel/files/8122283/Reporte.de.prototipo.RA.pdf)

**Comment by Nancy2050** [comment]
Puntaje: 20/20

**Comment by josealfredo79** [comment]
Bien hecho y revisado
